apiVersion: apps/v1
kind: Deployment
metadata:
  name: homework-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: homework
  template:
    metadata:
      labels:
        app: homework
    spec:
      containers:
      - name: web-container
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.port }}
        volumeMounts:
        - name: shared-volume
          mountPath: /homework
      volumes:
      - name: shared-volume
        emptyDir: {}