apiVersion: v1
kind: Service
metadata:
  name: homework-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: homework
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.port }}