# Необходимо создать манифест pod.yaml. Он должен описывать под, который:
# Будет создаваться в namespace homework
# Будет иметь контейнер, поднимающий веб-сервер на 8000 порту и отдающий содержимое папки /homework внутри этого контейнера.
# Будет иметь init-контейнер, скачивающий или генерирующий файл index.html и  сохраняющий его в директорию /init
# Будет иметь общий том (volume) для основного и init-контейнера, монтируемый в директорию /homework первого и /init второго
# Будет удалять файл index.html из директории /homework основного контейнера, перед его завершением
apiVersion: v1
kind: Pod
metadata:
  name: homework-pod
  namespace: homework
spec:
  initContainers:
  - name: init-container
    image: busybox
    command:
      - sh
      - -c
      - "echo '<h1>Hello from Kubernetes!</h1>' > /init/index.html"
    volumeMounts:
    - name: shared-volume
      mountPath: /init
  containers:
  - name: web-container
    image: nginx
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: shared-volume
      mountPath: /homework
    lifecycle:
      preStop:
        exec:
          command: ["rm", "-f", "/homework/index.html"]
  volumes:
  - name: shared-volume
    emptyDir: {}